Using Cross Validation to see what model works the best

In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [5]:
iris = load_iris()

**Logistic Regression**

In [9]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\linear_model\logist

array([0.96078431, 0.92156863, 0.95833333])

In [10]:
np.average(l_scores)

0.9468954248366014

**Decision Tree**

In [11]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.98039216, 0.92156863, 0.97916667])

In [12]:
np.average(d_scores)

0.960375816993464

**Support Vector Machine(SVM)**

In [13]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma

array([0.98039216, 0.96078431, 0.97916667])

In [14]:
np.average(s_scores)

0.9734477124183006

**Random Forest**

In [15]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=10), iris.data, iris.target)
r_scores

C:\Users\Pavlo\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.98039216, 0.94117647, 0.95833333])

In [16]:
np.average(r_scores)

0.9599673202614379